# Generated by Django 4.1.1 on 2023-04-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_company_options_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='inn',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Админ'), (2, 'Пользователь'), (3, 'Логист')], default=2, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.company', verbose_name='company'),
        ),
    ]
