# Generated by Django 4.1.1 on 2023-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_attachment_type_alter_auction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создана'), (1, 'Принята'), (2, 'В пути'), (3, 'Доставлена'), (4, 'Отменена')], default=0, verbose_name='Статус'),
        ),
    ]
